# Sample Bio Datasets Config

# datasets:
#   dataset_name:              <- A unique identifier for the dataset. This name is used to reference the dataset programmatically.
#       file_id:               <- The Google Drive file ID associated with the dataset. This is used for downloading the file.
#       filename:              <- The desired local filename (including extension) after the file is downloaded.

datasets:
  cell_subsampled:
    file_id: 1BH9nm4l6KeMM8g7Tr4OFWi6CRw5gKI1V
    filename: cell_subsampled.csv

  pivot:
    file_id: 1aaz4_Bos_lVQTWDq_q15j_3VRNNBmxW6
    filename: pivot.csv

  result:
    file_id: 1oT6E8UfDJyuksUf76yM84D5R5bm5nYHF
    filename: result.csv

  cluster_to_cluster_annotation_membership_pivoted:
    file_id: 1raE1Lhbk-zV0f2MOJybrwI-OhbSjpJBm
    filename: cluster_to_cluster_annotation_membership_pivoted.csv

  cell_metadata:
    file_id: 1bnjFi8EvTe1Dr3YYZzRmwN1pPgMgbgk_
    filename: cell_metadata.csv